-- ---------------------------------------------------------------------------
-- READ-ONLY diagnostic script — run this in the Supabase SQL editor and
-- share the output. Nothing here modifies data or schema.
--
-- Goal: confirm the actual column types / existing data before writing the
-- schema-consolidation migration (organizer_id FK unification + resolving
-- the 009_add_time_slots_to_availability vs 009_create_availability_slots
-- conflict).
-- ---------------------------------------------------------------------------

-- 1. Column types for every organizer_id-like column across the schema.
select table_name, column_name, data_type, udt_name, is_nullable
from information_schema.columns
where column_name in ('organizer_id', 'id')
  and table_schema = 'public'
  and table_name in ('organizers', 'appointments', 'bookings', 'availability',
                      'availability_exceptions', 'booking_settings', 'blocked_dates')
order by table_name, column_name;

-- 2. Does the legacy JSONB `time_slots` column still exist on availability?
select column_name, data_type
from information_schema.columns
where table_schema = 'public' and table_name = 'availability';

-- 3. Existing FK constraints already in place (if any) referencing organizers.
select tc.table_name, tc.constraint_name, kcu.column_name, ccu.table_name as references_table
from information_schema.table_constraints tc
join information_schema.key_column_usage kcu on tc.constraint_name = kcu.constraint_name
join information_schema.constraint_column_usage ccu on tc.constraint_name = ccu.constraint_name
where tc.constraint_type = 'FOREIGN KEY' and tc.table_schema = 'public';

-- 4. Sample of bookings.organizer_id values — are they real organizers.id
--    UUIDs, or the legacy hardcoded config id ('fred-eizo-001')?
select organizer_id, count(*) from bookings group by organizer_id;

-- 5. Sample of appointments.organizer_id values.
select organizer_id, count(*) from appointments group by organizer_id;

-- 6. Do organizers.id values look like UUIDs (they should, if generated by
--    Supabase's default gen_random_uuid())?
select id, name, slug, shopify_connection_id from organizers limit 20;
