# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "EIZO Rendez-vous"
client_id = "7ab91397ef48e5812a5dc2646820b0df"
application_url = "https://eizo-rendezvous-api-vercel-app.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,write_metaobjects"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://eizo-rendezvous-api-vercel-app.vercel.app/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
subpath = "booking"
prefix = "apps"
url = "https://eizo-rendezvous-api-vercel-app.vercel.app/api/proxy"

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true
